feat(clients): add Kotlin API client
algolia/api-clients-automation pull request #1400
Opened 2023-03-14 10:05 UTC by aallam

## 🧭 What and Why

Generation of Kotlin API Client with the following specification:

- Using Kotlin Multiplatform. First targets are JVM and iOS.
- `kotlinx.serialization` for serialization. 
- Ktor client as HTTP client.

🎟 JIRA Ticket:

APIC-651
APIC-652

### Changes included:

- [x] Clients generation
  - [x] Abtesting
  - [x] Analytics
  - [x] Ingestion
  - [x] Insights
  - [x] Personalization
  - [x] Predict
  - [x] QuerySuggestions
  - [x] Recommend
  - [x] Search
- [x] Playgound
- [x] CTS

2023-03-16 15:23 UTC, millotp reviewed
looks really nice ! First pass on the form of the PR, there is too much to look at everything ahah, GG !

2023-03-16 15:23 UTC, millotp commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/api/SearchApi.kt
those file are generated and you don't need to commit them :) you can filter them using the git hook and the file `config/generation.config.js`

2023-03-16 15:23 UTC, millotp commented on tests/output/java/bin/test/com/algolia/methods/requests/SearchClientRequestsTests.class
should you add `bin` to the .gitignore ?

2023-03-16 15:23 UTC, millotp commented on config/generation.config.js
> +    '!clients/algoliasearch-client-kotlin/**',
ah you added it already, did you run `yarn postinstall`to setup husky ?

2023-03-17 09:35 UTC, aallam commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/api/SearchApi.kt
Yes, definitely!

2023-03-17 09:36 UTC, aallam commented on tests/output/java/bin/test/com/algolia/methods/requests/SearchClientRequestsTests.class
Indeed, all compiled files shouldn't be included.

2023-04-19 07:26 UTC, millotp reviewed
amazing work !

2023-04-19 07:26 UTC, millotp commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/BuildConfig.kt
> +  internal const val version: String = "3.0.0-SNAPSHOT"
same here

2023-04-19 07:26 UTC, millotp commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/configuration/internal/HttpClient.kt
> +private const val HeaderApplicationID = "x-algolia-application-id"
we use `X-Algolia-Application-Id` in the spec and java, and the lower case in other languages, we should settle for one, you pick !

2023-04-19 07:26 UTC, millotp commented on generators/gradle/wrapper/gradle-wrapper.properties
why can't we reuse the root gradle file ?
also could you make this the same version as the rest pls ?

2023-04-19 07:26 UTC, millotp commented on generators/src/main/java/com/algolia/codegen/AlgoliaKotlinGenerator.java
> +      model.vendorExtensions.put("x-is-one-of-interface", true);
do you think it's possible to use common code with the java generator for future languages ?

2023-04-19 07:26 UTC, millotp commented on generators/src/main/java/com/algolia/codegen/Utils.java
> +      System.out.println("FOUND: " + CUSTOM_METHOD);
I don't think this debug log is necessary anymore

2023-04-19 07:26 UTC, millotp commented on generators/src/main/java/com/algolia/codegen/cts/AlgoliaCTSGenerator.java
> +    super.postProcessParameter(parameter);
this is debug also ?

2023-04-19 07:26 UTC, millotp commented on playground/kotlin/gradle/wrapper/gradle-wrapper.properties
same here, not possible to use the root one ?

2023-04-19 07:26 UTC, millotp commented on playground/kotlin/bin/main/com/algolia/playground/Predict.kt
should the bin folder be in `.gitignore` ? this feels like duplicate

2023-04-19 07:26 UTC, millotp commented on specs/abtesting/paths/abtests.yml
as we talked about during the meeting review this can be in a separate PR, just making a comment not to forget :)

2023-04-19 07:26 UTC, millotp commented on templates/kotlin/licenseInfo.mustache
> +// This class is auto generated.
can you remove this in favor of [generationBanner](https://api-clients-automation.netlify.app/docs/contributing/add-new-language#generated-file-banner) pls ?

2023-04-19 07:49 UTC, shortcuts commented on templates/kotlin/licenseInfo.mustache
> +// This class is auto generated.
just realized the link on the doc is wrong :( you can use it like that @aallam https://github.com/algolia/api-clients-automation/blob/main/templates/javascript/clients/api-single.mustache#L1

2023-04-20 08:31 UTC, aallam commented on clients/algoliasearch-client-kotlin/client-bom/README.md
> +    implementation platform('com.algolia:algoliasearch-client-kotlin-bom:3.0.0-SNAPSHOT')
Oh yes, for sure!

2023-04-20 08:31 UTC, aallam commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/BuildConfig.kt
> +  internal const val version: String = "3.0.0-SNAPSHOT"
It is generated indeed, forgot to exclude it from git

2023-04-20 08:33 UTC, aallam commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/configuration/internal/HttpClient.kt
> +private const val HeaderApplicationID = "x-algolia-application-id"
I've used uppercase in the start, then changed it to lowercase because of CTS tests 😅

2023-04-20 08:38 UTC, aallam commented on generators/gradle/wrapper/gradle-wrapper.properties
We don't have a shared root Gradle configuration for all Gradle projects, which includes the generator, Java, Kotlin, their CTS, and playgrounds. I'm not sure if it will work, but I can give it a try in another PR.

2023-04-20 08:40 UTC, aallam commented on generators/src/main/java/com/algolia/codegen/AlgoliaKotlinGenerator.java
> +      model.vendorExtensions.put("x-is-one-of-interface", true);
Perhaps, I think we should start by placing each language in its own subdirectory (in order to extract utility functions, and keep them in the correct scope). Then, when a few functions are shared, we can move them to a "utils" directory for reuse.

2023-04-20 08:42 UTC, aallam commented on playground/kotlin/bin/main/com/algolia/playground/Predict.kt
yup, should be ignored for sure.

2023-04-28 16:10 UTC, aallam commented
Waiting for #1492

2023-05-02 15:41 UTC, millotp reviewed
Nice !
I think there is an issue with the CI, there is no code generated, can you try to bump the cache key pls ?

2023-05-02 16:00 UTC, millotp commented
ah maybe it's not a cache key issue but a artifacts issue, we use them to pass file from jobs to jobs in the CI, you need to add one for kotlin in `.github/actions/restore-artifacts/action.yml`

2023-05-02 16:14 UTC, Fluf22 reviewed
Just a question following up @millotp remarks about versioning!

Otherwise, it looks really great!! Amazing work 🙌🏻

2023-05-02 17:38 UTC, shortcuts reviewed
This looks super clean, gg!

2023-05-02 17:38 UTC, shortcuts commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/configuration/Configuration.kt
> +  public val writeTimeout: Long
Should we precise we expect MS?

2023-05-04 08:53 UTC, aallam commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/configuration/Configuration.kt
> +  public val writeTimeout: Long
Actually, we can do even better, use [Duration](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/)!

2023-05-04 09:33 UTC, shortcuts commented on clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/configuration/Configuration.kt
> +  public val writeTimeout: Long
awesome!

2023-05-04 10:24 UTC, shortcuts approved these changes
Nothing to add on my side, SHIP IT!!

2023-05-04 10:26 UTC, shortcuts requested changes
actually can you bump this value? https://github.com/algolia/api-clients-automation/blob/main/.github/.cache_version

so we get a full CI run

2023-05-04 14:16 UTC, millotp submitted a review, later dismissed
i'm sorry I didn't except the CI to be that complicated, maybe it's easier if you make it work in another PR, this one is already huge and awesome, let's start with that ! 

To make the CI push the generated code you need to edit the `setRunVariables.ts` file to export a `RUN_GEN_KOTLIN` var

2023-05-04 14:49 UTC, aallam commented
@millotp Hopefully this time is the one 😅 otherwise I will make another PR for the CI

2023-05-04 14:53 UTC, millotp approved these changes
looks like there is still something missing, but I'm not sure why

2023-05-04 14:56 UTC, merged