docs(specs): review Insights API spec
algolia/api-clients-automation pull request #1647
Opened 2023-06-20 16:08 UTC by kai687

## 🧭 What and Why

Review and refine the OpenAPI specification for the Insights API.

🎟 JIRA Ticket: [DOC-1110]

### Changes included:

- [x] Correct parameter limits (maxItems for array types, maxLength for strings)
- [x] Updated API, operation, and parameter descriptions and summaries
- [x] Correct responses
- [x] Example requests and responses, particularly errors
- [x] Separate request bodies for allowed combinations of event attributes

## 🧪 Test

[DOC-1110]: https://algolia.atlassian.net/browse/DOC-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-21 08:59 UTC, gazconroy requested changes
Some questions and tiny suggestions

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/common/schemas/EventAttributes.yml
> +    > **Note**: Never include personally identifiable information in user tokens.
Such callouts are useful. Are we happy to document this form in our style guide?

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/common/schemas/EventAttributes.yml
> +    Time of the event in milliseconds in [Unix epoch time](https://en.wikipedia.org/wiki/Unix_time).
```suggestion
    Time of the event in milliseconds in [Unix epoch time](https://wikipedia.org/wiki/Unix_time).
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/common/schemas/EventAttributes.yml
> +  description: List of object identifiers for items of an Algolia index.
Normally, I'd avoid "List of" because the array type implies this. However, in this case, it reads awkwardly if "list of" is removed

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/common/schemas/EventAttributes.yml
> +    List of facet filters.
```suggestion
    Facet filters.
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/common/schemas/EventsResponse.yml
> +    description: Details about the response, such as, error messages.
```suggestion
    description: Details about the response, such as error messages.
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +                **All** events must be valid or the API returns an error.
```suggestion
                **All** events must be valid, otherwise the API will return an error.
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +              value: {'status': 404, 'message': 'Path not supported by Insights REST API. Please have a look at [https://www.algolia.com/doc/rest-api/insights/](https://www.algolia.com/doc/rest-api/i
```suggestion
              value: {'status': 404, 'message': 'Path not supported by Insights REST API. Check the list of [valid commands](https://www.algolia.com/doc/rest-api/insights/).'}
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +    but the request body must be smaller than 2MB.
```suggestion
    but the request body must be smaller than 2&nbsp;MB.
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +              value: {'status': 422, 'message': 'EventName must contain only visible ascii characters, and be between 1 and 64 characeters long'}
```suggestion
              value: {'status': 422, 'message': 'EventName must contain only visible ASCII characters, and be between 1 and 64 characters long'}
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +              value: {'status': 422, 'message': 'Event of type click with positions should specify a queryID'}
```suggestion
              value: {'status': 422, 'message': 'Event of type "click with positions" should specify a queryID'}
```
"Click with positions" or "click"?

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +              description: Any value in the `positions` array must be greater than or equal to 1.
```suggestion
              description: Any value in the `positions` array must be greater than 0.
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +              value: {'status': 422, 'message': 'Event of type click may only have strictly positive positions'}
A bit more convoluted than the description

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +              value: {'status': 422, 'message': 'Query ID must be a search query ID (32 characters hexadecimal string)'}
```suggestion
              value: {'status': 422, 'message': 'Query ID must be a search query ID (32 character hexadecimal string)'}
```

2023-06-21 08:59 UTC, gazconroy commented on specs/insights/paths/pushEvents.yml
> +              value: {'status': 422, 'message': 'Cannot process more than 1000 events in a batch'}
```suggestion
              value: {'status': 422, 'message': 'Cannot process more than 1,000 events in a batch'}
```

2023-06-21 10:00 UTC, shortcuts commented
> @shortcuts I exchanged `anyOf` with `oneOf` and _most_ checks work, except some tests. `oneOf` is the correct semantics here, since any event can only match one schema exactly.
> 
> What do you think about this?

This looks correct indeed, I wonder why [this test](https://github.com/algolia/api-clients-automation/blob/main/tests/CTS/methods/requests/insights/pushEvents.json) doesn't work for Java. Could you double check properties properly match their type etc.?

2023-06-21 12:08 UTC, shortcuts commented
> @shortcuts This is why the test fails:
> 
> ```
>  ClickedObjectIDsAfterSearch events_12 = new ClickedObjectIDsAfterSearch();
>         {
>           ClickEvent eventType3 = ClickEvent.fromValue("view");
>           events_12.setEventType(eventType3);
>           String eventName3 = "Product Detail Page Viewed";
>           events_12.setEventName(eventName3);
>           String index3 = "products";
>           events_12.setIndex(index3);
>           String userToken3 = "user-123456";
>           events_12.setUserToken(userToken3);
>           long timestamp3 = 1641290601962L;
>           events_12.setTimestamp(timestamp3);
>           List<String> objectIDs3 = new ArrayList<>();
>           {
>             String objectIDs_04 = "9780545139700";
>             objectIDs3.add(objectIDs_04);
>             String objectIDs_14 = "9780439784542";
>             objectIDs3.add(objectIDs_14);
>           }
>           events_12.setObjectIDs(objectIDs3);
>         }
> ```
> 
> It's a view event, but it uses the request body for `ClickedObjectIDsAfterSearch`. It should use `ViewedObjectIDs` instead (likewise for the conversion test).

Ah yessss there's an issue with the oneOf in the CTS that will pick the first `oneOf` type available if it can't correlate it correctly, cc @millotp

2023-06-22 07:20 UTC, shortcuts commented
Ok so I can confirm this is definitely a test generation issue, I'll push a fix to your branch sorry for the blocker

2023-06-22 08:58 UTC, shortcuts commented
https://github.com/algolia/api-clients-automation/pull/1654 fixes the CTS generation for this PR

2023-06-22 09:19 UTC, gazconroy submitted a review, later dismissed

2023-06-22 13:04 UTC, shortcuts commented
so sadly https://github.com/algolia/api-clients-automation/pull/1654 fixes this PR issue but would create a new problem :( so I just removed the test for now and will investigate

2023-06-22 14:41 UTC, shortcuts approved these changes
Huge! It's kind of a breaking change but it's the best time to provide them :D

thanks for a lot for the review

2023-06-22 14:55 UTC, merged