feat(specs): add OpenAPI spec for Monitoring API
algolia/api-clients-automation pull request #1683
Opened 2023-07-03 14:57 UTC by kai687

## 🧭 What and Why

Create an OpenAPI specification for the Monitoring API. 
The Monitoring API is HTTP only and isn't included in the API clients.

🎟 JIRA Ticket: [DOC-1132] https://algolia.atlassian.net/browse/DI-1419

[DOC-1132]: https://algolia.atlassian.net/browse/DOC-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-04 06:45 UTC, millotp commented
Hey, is it bad if the Monitoring API client is generated ? Or is it something that should not be generated ?

2023-07-04 07:02 UTC, shortcuts commented
@kai687 I've added the required stuff to make the CI and local tooling recognize the monitoring spec, it might not be enough to do the generation but as of now it already runs the build and linter steps on the specs, so that's great to progress on writing it!

2023-07-04 07:02 UTC, shortcuts commented
> Hey, is it bad if the Monitoring API client is generated ? Or is it something that should not be generated ?

Today there's none, but the API is documented, so we can generate it

2023-07-04 08:28 UTC, gazconroy requested changes
A few suggestions and a question

2023-07-04 08:28 UTC, gazconroy commented on specs/monitoring/common/responses/InfrastructureResponse.yml
> +              description: RAM usage for the indexing in MB.
```suggestion
              description: RAM used for indexing in MB.
```

2023-07-04 08:28 UTC, gazconroy commented on specs/monitoring/common/responses/InfrastructureResponse.yml
> +              description: RAM usage for the search in MB.
```suggestion
              description: RAM used for search in MB.
```

2023-07-04 08:28 UTC, gazconroy commented on specs/monitoring/common/schemas/Incidents.yml
> +      description: Timestamp of the incident report.
```suggestion
      description: Timestamp of the incident report.
```
For this and other times, what's the timestamp format? Unix epoch time in seconds?

2023-07-04 08:28 UTC, gazconroy commented on specs/monitoring/common/parameters.yml
> +    To include all metrics, use `*` as parameter.
```suggestion
    To include all metrics, use `*` as the parameter.
```

2023-07-04 08:28 UTC, gazconroy commented on specs/monitoring/paths/getInventory.yml
> +    The response depends whether you authenticate your API request:
```suggestion
    The response depends on whether you authenticate your API request:
```

2023-07-04 08:28 UTC, gazconroy commented on specs/monitoring/paths/getReachability.yml
> +  summary: Test reachability of clusters.
```suggestion
  summary: Test the reachability of clusters.
```

2023-07-04 08:28 UTC, gazconroy commented on specs/monitoring/paths/getStatus.yml
> +  summary: List statuses of clusters.
```suggestion
  summary: List cluster statuses.
```

2023-07-04 12:59 UTC, shortcuts commented
@kai687 I found the issue for the java generation, this should be good now!

2023-07-04 14:22 UTC, shortcuts commented
Ah we force having tests for a client D: so it will fail again, a bit more annoying than estimated ahaha

2023-07-04 14:36 UTC, shortcuts commented on specs/monitoring/spec.yml
> +    $ref: 'paths/getMetrics.yml'
can we use plural/singular form instead? e.g. `getStatuses`, `getStatus`?

does it make sense to you? Single is a bit vague IMHO, especially since it will also be the name of the methods in the clients

----

alternative: `listStatus` | `getStatus`, list implies many, get implies a single entity

2023-07-04 14:37 UTC, shortcuts commented on specs/monitoring/paths/getStatus.yml
> +    - apiKey: []
are those required? the scheme in `spec.yml` should be enough I believe

2023-07-04 14:55 UTC, shortcuts commented on specs/monitoring/paths/getStatus.yml
> +    - apiKey: []
ahhh ok that make total sense then

2023-07-04 15:02 UTC, millotp commented on specs/monitoring/spec.yml
> +    $ref: 'paths/getMetrics.yml'
`listStatus` and `listStatusForCluster` ?

2023-07-04 15:02 UTC, millotp commented on specs/monitoring/spec.yml
> +    $ref: 'paths/getMetrics.yml'
`listStatusByCluster` ?

2023-07-04 15:29 UTC, aallam commented on config/openapitools.json
> +        }
```suggestion
```

Dart API client is currently in its early stages and currently supports only search and insights.
We can consider adding additional clients once the client is more mature.

2023-07-04 15:32 UTC, shortcuts commented on config/openapitools.json
> +        }
do you think it's a blocker of adding it right now? the endpoints are pretty standard so I guess there's no risk of exposing that

2023-07-04 15:35 UTC, aallam commented on config/openapitools.json
> +        }
I don't have a strong preference regarding this. I simply think there are other clients that should be prioritized before adding this one, thats all :)

2023-07-04 15:37 UTC, shortcuts commented on config/openapitools.json
> +        }
if we see it fail on the gen, build or cts step we can omit it, otherwise I believe it's fine

2023-07-06 06:43 UTC, shortcuts commented
@kai687 do you need help for the CI?

2023-07-06 06:54 UTC, shortcuts commented
> I guess, I need to add tests for every operation. I'll see how far I can get.

I added tests in https://github.com/algolia/api-clients-automation/pull/1683/commits/911089b0deab2dbdd357c1de8104b9cb398bd581, however it was before the changes you made so if you can take a small look at them and see if they are correct it would be enough I guess

2023-07-06 08:18 UTC, shortcuts commented
@kai687 the CI fails because the tests I wrote were before the rename of the methods

2023-07-10 15:27 UTC, shortcuts commented
ok wow I found a looooot of bugs in this PR, so glad you did it and sorry for all the commits :D

I'm moving unrelated changes to its own PR, then doing a cleanup

2023-07-11 10:02 UTC, millotp commented on clients/algoliasearch-client-javascript/yarn.lock
> +"@algolia/monitoring@workspace:packages/monitoring":
isn't that file generated ?

2023-07-11 10:03 UTC, shortcuts commented on scripts/ci/utils.ts
> +        `git add -N . && git diff --shortstat ${branch}${checkHead} -- ${path} | wc -l`,
if you do the diff it will not show the untracked ones 🤷🏻

2023-07-11 10:06 UTC, millotp commented on scripts/ci/utils.ts
> +        `git add -N . && git diff --shortstat ${branch}${checkHead} -- ${path} | wc -l`,
wasn't aware of that ! Interesting

2023-07-11 10:07 UTC, shortcuts commented on scripts/ci/utils.ts
> +        `git add -N . && git diff --shortstat ${branch}${checkHead} -- ${path} | wc -l`,
yup and today basically if there was no files in a given folder, it wouldn't be added, so this fixes many other issues actually which is super niceeee

2023-07-11 10:07 UTC, merged