docs(specs): Review OpenAPI Search API (synonym operations)
algolia/api-clients-automation pull request #1699
Opened 2023-07-06 12:13 UTC by gazconroy

## 🧭 What and Why

This is one of several PRs addressing the Search API.

This PR reviews just the synonym operations of the Search API.

### Questions and notes

#### saveSynonyms

You can add synonym objectIDs in the path parameter and the body parameter. It appears that the objectID in the body parameter takes precedence. Is that always the case?

🎟 JIRA Ticket: [DOC-1107](https://algolia.atlassian.net/browse/DOC-1107)

### Changes included:

Changes to summary, description and examples

## 🧪 Test

2023-07-13 09:55 UTC, shortcuts requested changes
nice :)

2023-07-13 09:55 UTC, shortcuts commented on specs/search/paths/synonyms/common/parameters.yml
> +ObjectID:
we should use the common one

2023-07-13 09:55 UTC, shortcuts commented on specs/search/paths/synonyms/common/parameters.yml
> +ObjectID:
https://github.com/algolia/api-clients-automation/blob/main/specs/common/parameters.yml#L11

2023-07-13 10:00 UTC, millotp commented
> It appears that the objectID in the body parameter takes precedence. Is that always the case ?

The body and path parameters are merged together for javascript, but maybe `openapi` merges then anyway because they have the same name ?

2023-07-13 10:03 UTC, millotp commented on specs/search/paths/synonyms/common/parameters.yml
> +ObjectID:
I think it's fine in this case, it's to improve documentation, and it doesn't create a new type (it's just translated to string), so there is no conflict.

2023-07-13 10:05 UTC, shortcuts commented on specs/search/paths/synonyms/common/parameters.yml
> +ObjectID:
I don't think there should be many definitions of an objectID

2023-07-13 10:57 UTC, shortcuts commented on specs/search/paths/synonyms/common/parameters.yml
> +ObjectID:
what changes is the context not the definition of the objectID 🤔 if you think it makes more sense then let's do it but I feel like it's more the responsibility of the documentation rather than the api spec definition

2023-07-14 08:06 UTC, gazconroy commented on specs/search/paths/synonyms/common/parameters.yml
> +ObjectID:
And there are also dictionary objects

2023-07-19 07:04 UTC, shortcuts approved these changes

2023-07-19 07:04 UTC, merged