fix(cts): test encoding of special characters
algolia/api-clients-automation pull request #2804
Opened 2024-02-29 16:13 UTC by millotp

## 🧭 What and Why

The `filters` property can use some special char, we need to make sure that every language has the same encoding

2024-02-29 16:13 UTC, shortcuts requested changes
good idea! just blocking in case of miss merge during release

2024-02-29 16:14 UTC, millotp commented
the CI will fail don't worry

2024-02-29 16:24 UTC, Fluf22 commented
Swift being green feelsgoodman.gif

2024-03-01 13:50 UTC, millotp commented
I give up, algolia accept both so I'll just adapt my tests

2024-03-01 13:50 UTC, closed without merging

2024-03-01 13:51 UTC, shortcuts commented
> I give up, algolia accept both so I'll just adapt my tests

oneof cts oneof cts!!!!!!!!!!!!!!!!