feat(specs): add ga4BigqueryExport, streaming and append options to task inputs
algolia/api-clients-automation pull request #2858
Opened 2024-03-12 07:40 UTC by JasonBerry

## 🧭 What and Why
GA4 BigQuery Export task type was added.

🎟 JIRA Ticket: EEX-1055

### Changes included:

- Add `ga4BigqueryExport` task type
- Add `streaming` trigger type
- Add `append` action type

## 🧪 Test

2024-03-12 07:49 UTC, jsok requested changes

2024-03-12 07:49 UTC, jsok commented on specs/ingestion/common/schemas/source.yml
> +    - datasetID
table prefix is required too

2024-03-12 07:49 UTC, jsok commented on specs/ingestion/common/schemas/source.yml
> +    table:
There is no table field on the source type, only table prefix.

2024-03-12 07:49 UTC, jsok commented on specs/ingestion/common/schemas/source.yml
> +      description: Table prefix (for Google Analytics).
This could be rewritten to match the GA4 docs a bit better.

Maybe "table prefix, e.g. events_ or events_intraday_ without the YYYYMMDD"

2024-03-12 22:40 UTC, jonathaningram commented on specs/ingestion/common/schemas/source.yml
> +      description: Project ID of the BigQuery Source.
```suggestion
      description: GCP project ID that the BigQuery Export writes to.
```

2024-03-12 22:40 UTC, jonathaningram commented on specs/ingestion/common/schemas/source.yml
> +      description: Dataset ID of the BigQuery Source.
```suggestion
      description: BigQuery dataset ID that the BigQuery Export writes to.
```

2024-03-12 22:40 UTC, jonathaningram commented on specs/ingestion/common/schemas/source.yml
> +      description: Table prefix (for Google Analytics).
If helpful, referring to https://support.google.com/analytics/answer/9358801?hl=en will help you write this better per jsok's suggestion.

2024-03-12 22:40 UTC, jonathaningram commented on specs/ingestion/common/schemas/source.yml
> +  x-discriminator-fields:
Out of interest, do you know how this works / what it does?

2024-03-13 00:26 UTC, shortcuts commented on specs/ingestion/common/schemas/source.yml
> +  x-discriminator-fields:
Strongly typed languages have a custom serializer/deserializer for oneOf schemas and the discriminator helps it matching the raw payload/reponse with the correct type if the key is found in it

2024-03-13 00:30 UTC, jonathaningram commented on specs/ingestion/common/schemas/source.yml
> +  x-discriminator-fields:
Right. In that case, I think we'd need more than just `projectID` here because `SourceBigQuery` also only has `projectID` in it?

2024-03-13 00:50 UTC, JasonBerry commented on specs/ingestion/common/schemas/source.yml
> +  x-discriminator-fields:
Yes, I think we should add `tablePrefix`?

2024-03-13 01:07 UTC, jonathaningram commented on specs/ingestion/common/schemas/source.yml
> +  x-discriminator-fields:
Yeah sounds like we should do that. I guess we can check what the generated clients look like and update it in a follow up if it's wrong.

2024-03-13 01:40 UTC, jonathaningram requested changes
build issue?

2024-03-13 02:11 UTC, jonathaningram approved these changes

2024-03-13 04:15 UTC, jsok approved these changes

2024-03-13 04:15 UTC, jsok commented on specs/ingestion/common/taskParameters.yml
> +  description: The sourceIDs of the tasks to retrieve.
❤️

2024-03-13 07:20 UTC, shortcuts approved these changes
Sorry I fell asleep ahah ty for the contribution!

2024-03-13 07:20 UTC, merged