chore(clients): add workflow to auto-close PR
algolia/api-clients-automation pull request #3834
Opened 2024-09-25 13:59 UTC by shortcuts

## 🧭 What and Why

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2970

### Changes included:

heavily inspired by https://github.com/algolia/doc/blob/master/.github/workflows/dont-edit-apis.yml, we can kindly ask the user to redirect their contributions to the automation repository, or ask them to open an issue if they don't want to.

2024-09-25 14:15 UTC, millotp requested changes
nice

2024-09-25 14:15 UTC, millotp commented on templates/do-not-edit-this-repository.yml
> +        run: |
you need to check that the PR is targeting, because it's possible to do bug fixes on older version

2024-09-25 14:16 UTC, shortcuts commented on templates/do-not-edit-this-repository.yml
> +        run: |
yup this should do it https://github.com/algolia/api-clients-automation/blob/b227ed49c43e9fe2ad4b05a1a64acff5a12b07d7/templates/do-not-edit-this-repository.yml#L3

2024-09-25 14:23 UTC, millotp commented on generators/src/main/java/com/algolia/codegen/AlgoliaDartGenerator.java
> +    supportingFiles.add(
we could have an helper to add the 4 common files, with the root folder as argument

2024-09-25 14:23 UTC, millotp commented on templates/do-not-edit-this-repository.yml
> +        run: |
oh sorry I missed that

2024-09-25 15:44 UTC, shortcuts commented
> Greatest achievement of my life. Someone was inspired by something I did 🤣.

<3

2024-09-26 15:03 UTC, shortcuts commented on generators/src/main/java/com/algolia/codegen/AlgoliaDartGenerator.java
> +    supportingFiles.add(
https://github.com/algolia/api-clients-automation/pull/3834/commits/a589dfa8f1088a1f84691a449273f2a9bfff6780 hopla

2024-09-26 15:37 UTC, millotp approved these changes
beautiful

2024-09-26 15:48 UTC, merged